# A simple action usage
name: Build Kernel
on:
  workflow_dispatch:

jobs:
  Build-Kernel:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - name: Build Kernel
      uses: dabao1955/kernel_build_action@main
      with:
          kernel-url: https://github.com/badelXia/android_kernel_xiaomi_thyme
          kernel-dir: msm-4.19
          kernel-branch: main
          config: thyme_defconfig
          arch: arm64
          aosp-gcc: true
          aosp-clang: true
          ksu: true
          ksu-version: main
          android-version: 11
          aosp-clang-version: r383902b
          disable-lto: true
          anykernel3: true
